# Generated by Django 5.1.1 on 2025-01-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halls',
            name='photo_url',
            field=models.FileField(upload_to=''),
        ),
    ]
