# Generated by Django 5.1.1 on 2025-01-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_alter_halls_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_image',
            field=models.FileField(upload_to=''),
        ),
    ]
