# Generated by Django 5.1.1 on 2025-01-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_food_food_name_alter_food_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='decoration_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
