# Generated by Django 5.1.1 on 2025-01-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_decoration_decoration_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='event_id',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
