# Generated by Django 5.1.1 on 2025-01-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_remove_bookings_event_id_delete_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='decoration_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='event_status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='food_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='no_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
